project:
  type: website
  output-dir: docs

website:
  title: "Wet lab data analysis"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: colorimetric.qmd
        text: "Colorimetric Data"
      - href: qpcr.qmd
        text: "qPCR Data"

format:
  html:
    theme: cosmo
    toc: true
